#!/usr/bin/env python3
"""PAOFLOW driver script (generated by paoflow_gen.py).

Edit the constants below and the property calls in the run function(s) to
customize the calculation.  Run with:

    python main.py
    # or, in parallel:
    mpirun -np <N> python main.py
"""

import os
import sys

from PAOFLOW import PAOFLOW
from PAOFLOW.basis_gen import generate_basis_for_pseudo
from PAOFLOW.basis_gen.driver import _default_shells
from PAOFLOW.inputs.read_upf import UPF as _UPFParser

try:
    from mpi4py import MPI

    RANK = MPI.COMM_WORLD.Get_rank()
except ImportError:
    RANK = 0


# ----------------------------------------------------------------------- #
# Configuration  (edit freely)                                            #
# ----------------------------------------------------------------------- #
HERE = os.path.dirname(os.path.abspath(__file__))
SAVEDIR = os.path.join(HERE, 'As1Ga1.save')
UPFS = [os.path.join(HERE, 'As1Ga1.save/As.upf'), os.path.join(HERE, 'As1Ga1.save/Ga.upf')]
BASISPATH = os.path.join(HERE, 'BASIS_PS') + os.sep
OUTPUTDIR = 'output'

NPOOL = 1
SMEARING = None
SPIN_ORBIT = False   # set True for spin-orbit (noncollinear) runs
STD_BASIS = 'standard'   # basis configuration for standard properties
PTHR = 0.95   # projectability threshold

IBRAV = 2
NK = 801   # k-points along the band path

# Energy grid for DOS / transport / Hall properties (eV, relative to E_F).
# The full PAO band range is printed as a suggestion at run time
# (see suggest_energy_window); edit these values to match your needs.
EMIN, EMAX, NE = -12.0, 6.1, 1000
DO_PDOS = False

# Double-grid interpolation (denser FFT grid). Set to None to skip.
NFFT = (32, 32, 32)


def ensure_basis(preset="extended"):
    """Generate the pseudo-atom basis under BASISPATH for every species.

    The 'extended' preset is a superset of 'standard' and 'minimal', so
    generating it once is enough for every configuration used below.
    """
    if RANK != 0:
        return
    for upf_path in UPFS:
        upf = _UPFParser(upf_path)
        element = upf.element.strip()
        elem_dir = os.path.join(BASISPATH, element)
        expected = _default_shells(upf, preset=preset)
        missing = [
            s for s in expected
            if not os.path.exists(os.path.join(elem_dir, "{}.dat".format(s)))
        ]
        if missing:
            print("Generating pseudo-atom basis for {} under {} ...".format(
                element, BASISPATH))
            generate_basis_for_pseudo(
                upf_path, BASISPATH.rstrip(os.sep), preset=preset, verbose=True
            )
        else:
            print("Using existing pseudo-atom basis for {} under {}".format(
                element, BASISPATH))


def suggest_energy_window(p):
    """Print the full PAO band range (eV, rel. to E_F) as a suggested window.

    Must be called after p.pao_eigh().  The eigenvalues ('E_k') are distributed
    across MPI ranks, so the local extrema are reduced to give every process the
    same global range.  This only prints a hint; the calculation uses the
    user-defined EMIN / EMAX / NE constants above.
    """
    import numpy as np

    E_k = p.data_controller.data_arrays['E_k']
    emin = float(np.amin(E_k))
    emax = float(np.amax(E_k))
    if "MPI" in globals():
        comm = MPI.COMM_WORLD
        emin = comm.allreduce(emin, op=MPI.MIN)
        emax = comm.allreduce(emax, op=MPI.MAX)
    if RANK == 0:
        print('Suggested energy window from PAO bands: '
              'EMIN={:.4f}, EMAX={:.4f} eV'.format(emin, emax))
        print('  (currently using EMIN={}, EMAX={}, NE={})'.format(EMIN, EMAX, NE))
    return emin, emax


def run_properties():
    """Standard properties on the standard basis."""
    p = PAOFLOW.PAOFLOW(
        workpath=HERE,
        outputdir=OUTPUTDIR,
        savedir=SAVEDIR,
        smearing=SMEARING,
        npool=NPOOL,
        verbose=False,
    )

    p.projections(basispath=BASISPATH, configuration=STD_BASIS)
    p.projectability(pthr=PTHR)
    p.pao_hamiltonian()

    p.bands(ibrav=IBRAV, nk=NK, fname='bands')

    if NFFT is not None:
        p.interpolated_hamiltonian(nfft1=NFFT[0], nfft2=NFFT[1], nfft3=NFFT[2])
    p.pao_eigh()

    # Print the full PAO band range as a suggested energy window.
    suggest_energy_window(p)

    p.gradient_and_momenta()
    p.adaptive_smearing()
    p.dos(do_dos=True, do_pdos=DO_PDOS, emin=EMIN, emax=EMAX, ne=NE)

    p.finish_execution()


def main():
    if not os.path.isdir(SAVEDIR):
        print("{} not found. Run pw.x (scf then nscf) first.".format(SAVEDIR))
        sys.exit(1)

    ensure_basis(preset='extended')
    if "MPI" in globals():
        MPI.COMM_WORLD.Barrier()

    run_properties()


if __name__ == "__main__":
    main()
