#!/usr/bin/env python3
"""Plotting helper for the PAOFLOW run (generated by paoflow_gen.py).

This script mirrors the property selection made when the PAOFLOW driver was
generated.  Run it after the PAOFLOW calculation has produced its output files
and pick what to plot from the menu:

    python plot.py

The energy window and property y-axis limits can be set on the command line:

    python plot.py --emin -5 --emax 5 --ymin 0 --ymax 100

and are also asked for interactively when the script runs (press Enter to keep
the default / command-line value).  EMIN/EMAX set the energy axis (vertical for
band plots, horizontal for the energy-resolved property plots) and default to
the window identified when the driver was generated.  YMIN/YMAX set the property
y-axis and default to automatic scaling.  Optical spectra always start at 0 on
the energy axis.

The plots use the helpers in PAOFLOW.GPAO.
"""

import argparse
import glob
import os
import sys

from PAOFLOW import GPAO


HERE = os.path.dirname(os.path.abspath(__file__))
OUTPUTDIR = os.path.join(HERE, 'output')

pplt = GPAO.GPAO()

# Default energy window (eV, relative to E_F) identified when the driver was
# generated.  Overridable on the command line via --emin/--emax.  YMIN/YMAX
# default to None (automatic axis limits) and can be set via --ymin/--ymax.
EMIN = -12.0
EMAX = 6.1
YMIN = None
YMAX = None


def _ewin():
    """Energy-axis window (EMIN, EMAX) used for band / energy-resolved plots."""
    return (EMIN, EMAX)


def _ewin_optical():
    """Energy-axis window for optical spectra (always starts at 0)."""
    return (0.0, EMAX)


def _ylim():
    """Property-axis limits (YMIN, YMAX), or None for automatic scaling."""
    if YMIN is None and YMAX is None:
        return None
    return (YMIN, YMAX)


def _dos_mag_lim(fnames):
    """Magnitude-axis limits for DOS/PDOS plots.

    When the user sets YMIN/YMAX those win.  Otherwise the magnitude axis is
    rescaled to the data that falls inside the chosen energy window [EMIN, EMAX]
    so that limiting the energy range actually zooms the curve (important for
    metals, whose largest DOS peaks may sit far outside the window).
    """
    if YMIN is not None or YMAX is not None:
        return _ylim()
    if isinstance(fnames, str):
        fnames = [fnames]
    import numpy as np

    peak = 0.0
    for fn in fnames:
        if not fn:
            continue
        try:
            data = np.loadtxt(fn)
        except (OSError, ValueError):
            continue
        if data.ndim != 2 or data.shape[1] < 2:
            continue
        es = data[:, 0]
        mag = data[:, 1:]
        mask = (es >= EMIN) & (es <= EMAX)
        if not mask.any():
            continue
        peak = max(peak, float(np.nanmax(np.abs(mag[mask]))))
    if peak <= 0.0:
        return None
    return (0.0, 1.1 * peak)



def _ask_float(prompt, default):
    """Prompt for a float, accepting Enter to keep *default* (may be None)."""
    shown = 'auto' if default is None else default
    try:
        raw = input('{} [{}]: '.format(prompt, shown)).strip()
    except EOFError:
        return default
    if raw == '':
        return default
    if raw.lower() in ('auto', 'none'):
        return None
    try:
        return float(raw)
    except ValueError:
        print('  (invalid number, keeping {})'.format(shown))
        return default



def _one(pattern):
    """Return the first OUTPUTDIR file matching *pattern* (or None).

    Patterns are written with an optional ``<prefix>.`` in front (e.g.
    ``*.bands_0.dat``).  PAOFLOW may write the files either with that prefix
    (``Si.bands_0.dat``) or without it (``bands_0.dat``), so a ``*.`` pattern
    falls back to the prefix-less form.
    """
    hits = sorted(glob.glob(os.path.join(OUTPUTDIR, pattern)))
    if not hits and pattern.startswith('*.'):
        hits = sorted(glob.glob(os.path.join(OUTPUTDIR, pattern[2:])))
    return hits[0] if hits else None


def _many(pattern):
    """Return all OUTPUTDIR files matching *pattern* (sorted).

    As with :func:`_one`, a ``*.`` pattern also matches prefix-less files.
    """
    hits = sorted(glob.glob(os.path.join(OUTPUTDIR, pattern)))
    if not hits and pattern.startswith('*.'):
        hits = sorted(glob.glob(os.path.join(OUTPUTDIR, pattern[2:])))
    return hits


def _missing(*names):
    """Warn about missing output files; return True if anything is missing."""
    gone = [n for n in names if n is None]
    if gone:
        print("  (output file(s) not found in {}; run PAOFLOW first)".format(OUTPUTDIR))
        return True
    return False


def _file_energy_range(fname):
    """Return (min, max) of the energy column of *fname*, or None."""
    if not fname:
        return None
    import numpy as np

    try:
        data = np.loadtxt(fname)
    except (OSError, ValueError):
        return None
    if data.ndim != 2 or data.shape[0] == 0:
        return None
    es = data[:, 0]
    return (float(np.nanmin(es)), float(np.nanmax(es)))


def _default_energy_window():
    """Default energy window for the prompts.

    When a DOS file is present its energy grid is used so that the DOS fills
    the side-by-side panel (the DOS is usually computed on a narrower grid than
    the bands).  Otherwise the window identified when the driver was generated
    is kept.
    """
    return _file_energy_range(_one('*.dosdk_0.dat'))


_SPIN_COLORS = ['tab:blue', 'tab:red', 'tab:green', 'tab:orange']


def _spin_channels(pattern):
    """Return ``([files], [labels])`` for the spin channels of *pattern*.

    The generated patterns target the first spin channel through a ``_0`` tag.
    A spin-polarized (nspin=2) run also writes the ``_1`` channel; when present
    both files are returned so the two channels can be overlaid in one figure.
    """
    f0 = _one(pattern)
    if f0 is None:
        return [], []
    files, labels = [f0], ['spin up']
    f1 = _one(pattern.replace('_0.', '_1.'))
    if f1 is not None:
        files.append(f1)
        labels.append('spin down')
    return files, labels


def _overlay_transport(files, labels, title, y_label, scale=1.0, min_zero=False):
    """Overlay the diagonal-averaged transport tensor of several files.

    Used for spin-polarized conductivity / Seebeck output, where each spin
    channel is written to its own file: both channels are drawn on a single
    figure (one line per spin and temperature).
    """
    import numpy as np
    import matplotlib.pyplot as plt
    from PAOFLOW.inputs.read_pao_output import read_transport_PAO

    fig = plt.figure()
    fig.suptitle(title)
    ax = fig.add_subplot(111)
    ic = 0
    ymax = 0.0
    for fn, base in zip(files, labels):
        enes, temps, tensors = read_transport_PAO(fn)
        for it, temp in enumerate(temps):
            trace = scale * np.einsum('eii->e', tensors[it]) / 3.0
            lbl = base if len(temps) == 1 else '{}, T={:g}'.format(base, temp)
            ax.plot(enes, trace, color=_SPIN_COLORS[ic % len(_SPIN_COLORS)], label=lbl)
            ymax = max(ymax, float(np.nanmax(np.abs(trace))))
            ic += 1
    ax.set_xlim(*_ewin())
    yl = _ylim()
    if yl is not None:
        ax.set_ylim(*yl)
    elif min_zero and ymax > 0.0:
        ax.set_ylim(0.0, 1.1 * ymax)
    ax.set_xlabel('Energy (eV)')
    ax.set_ylabel(y_label)
    ax.legend()
    plt.show()


def _overlay_bands_dos(band_files, dos_files, labels, sym_file, title):
    """Bands beside DOS with both spin channels overlaid on one figure.

    Reproduces ``plot_dos_beside_bands`` but loops over the spin channels so
    that the two channels share a single bands panel and a single DOS panel.
    """
    import numpy as np
    import matplotlib.pyplot as plt
    from matplotlib import gridspec
    from PAOFLOW.inputs.read_pao_output import (
        read_bands_PAO,
        read_dos_PAO,
        read_band_path_PAO,
    )

    sym_points = read_band_path_PAO(sym_file) if sym_file else None
    y_lim = _ewin()

    fig = plt.figure()
    spec = gridspec.GridSpec(ncols=2, nrows=1, width_ratios=[5, 1])
    fig.suptitle(title)
    ax_b = fig.add_subplot(spec[0])
    ax_d = fig.add_subplot(spec[1])

    nk = 1
    dos_peak = 0.0
    for i, (fb, fd, lbl) in enumerate(zip(band_files, dos_files, labels)):
        col = _SPIN_COLORS[i % len(_SPIN_COLORS)]
        bands = read_bands_PAO(fb)
        nk = bands.shape[1]
        for j, b in enumerate(bands):
            ax_b.plot(b, color=col, label=lbl if j == 0 else None)
        es, dos = read_dos_PAO(fd)
        ax_d.plot(dos, es, color=col, label=lbl)
        mask = (es >= y_lim[0]) & (es <= y_lim[1])
        if mask.any():
            dos_peak = max(dos_peak, float(np.nanmax(np.abs(dos[mask]))))

    ax_b.set_xlim(0, nk - 1)
    ax_b.set_ylim(*y_lim)
    if sym_points is None:
        ax_b.xaxis.set_visible(False)
    else:
        ax_b.set_xticks(sym_points[0])
        ax_b.set_xticklabels(sym_points[1])
        ax_b.vlines(sym_points[0], y_lim[0], y_lim[1], color='gray')
    ax_b.set_ylabel(r'$\epsilon$($\mathbf{k}$) (eV)', fontsize=12)
    ax_b.legend()

    xl = _ylim()
    if xl is not None:
        ax_d.set_xlim(*xl)
    elif dos_peak > 0.0:
        ax_d.set_xlim(0.0, 1.1 * dos_peak)
    ax_d.set_ylim(*y_lim)
    ax_d.yaxis.set_visible(False)
    ax_d.set_xlabel('DOS')

    plt.tight_layout()
    plt.show()


def plot_band_structure():
    files, labels = _spin_channels('*.bands_0.dat')
    sp = _one('*.kpath_points.txt')
    if not files:
        _missing(None)
        return
    if len(files) > 1:
        pplt.plot_bands(files, sym_points=sp, title='Band structure',
                        y_lim=_ewin(), labels=labels, cols=_SPIN_COLORS[:len(files)])
    else:
        pplt.plot_bands(files[0], sym_points=sp, title='Band structure', y_lim=_ewin())

def plot_density_of_states():
    files, labels = _spin_channels('*.dosdk_0.dat')
    if not files:
        _missing(None)
        return
    if len(files) > 1:
        pplt.plot_pdos(files, title='Density of states', x_lim=_ewin(),
                       y_lim=_dos_mag_lim(files), labels=labels)
    else:
        pplt.plot_dos(files[0], title='Density of states', x_lim=_ewin(), y_lim=_dos_mag_lim(files[0]))

def plot_bands_and_dos():
    bfiles, blabels = _spin_channels('*.bands_0.dat')
    dfiles, _ = _spin_channels('*.dosdk_0.dat')
    sp = _one('*.kpath_points.txt')
    if not bfiles or not dfiles:
        _missing(None)
        return
    if len(bfiles) > 1 and len(dfiles) > 1:
        _overlay_bands_dos(bfiles, dfiles, blabels, sp,
                           title='Bands and DOS')
    else:
        pplt.plot_dos_beside_bands(dfiles[0], bfiles[0], sym_points=sp, dos_ticks=True,
                                   title='Bands and DOS', x_lim=_dos_mag_lim(dfiles[0]), y_lim=_ewin())

# Ordered menu of available plots: (label, function).
PLOTS = [
    ('Band structure', plot_band_structure),
    ('DOS / projected DOS', plot_density_of_states),
    ('Bands + DOS (side by side)', plot_bands_and_dos),
]


def main():
    global EMIN, EMAX, YMIN, YMAX
    parser = argparse.ArgumentParser(
        description='Plot PAOFLOW results with optional axis limits.')
    parser.add_argument('--emin', type=float, default=None,
                        help='Lower energy-axis limit (eV, rel. E_F).')
    parser.add_argument('--emax', type=float, default=None,
                        help='Upper energy-axis limit (eV, rel. E_F).')
    parser.add_argument('--ymin', type=float, default=None,
                        help='Lower property y-axis limit (default: automatic)')
    parser.add_argument('--ymax', type=float, default=None,
                        help='Upper property y-axis limit (default: automatic)')
    args = parser.parse_args()
    # Default the energy window to the DOS data range (so the DOS fills the
    # side-by-side panel) unless it was overridden on the command line.
    _win = _default_energy_window() or (EMIN, EMAX)
    EMIN = args.emin if args.emin is not None else _win[0]
    EMAX = args.emax if args.emax is not None else _win[1]
    YMIN, YMAX = args.ymin, args.ymax
    # Ask for the axis limits interactively (Enter keeps the shown default;
    # any value passed on the command line becomes that default).
    print('Axis limits (press Enter to accept the default):')
    EMIN = _ask_float('  Energy axis EMIN (eV, rel. E_F)', EMIN)
    EMAX = _ask_float('  Energy axis EMAX (eV, rel. E_F)', EMAX)
    YMIN = _ask_float('  Property axis YMIN (auto for automatic)', YMIN)
    YMAX = _ask_float('  Property axis YMAX (auto for automatic)', YMAX)
    print('Available plots:')
    for i, (label, _fn) in enumerate(PLOTS, 1):
        print('  {}: {}'.format(i, label))
    try:
        raw = input("Enter a comma/space separated list (or 'all'): ").strip()
    except EOFError:
        raw = ''
    if raw.lower() == 'all':
        chosen = list(range(1, len(PLOTS) + 1))
    else:
        chosen = []
        for tok in raw.replace(',', ' ').split():
            try:
                idx = int(tok)
            except ValueError:
                continue
            if 1 <= idx <= len(PLOTS) and idx not in chosen:
                chosen.append(idx)
    if not chosen:
        print('Nothing selected.')
        return
    for idx in chosen:
        label, fn = PLOTS[idx - 1]
        print('\n== {} =='.format(label))
        fn()


if __name__ == "__main__":
    main()
