#!/usr/bin/env python3
"""PAOFLOW driver script (generated by paoflow_gen.py).

Edit the constants below and the property calls in the run function(s) to
customize the calculation.  Run with:

    python main.py
    # or, in parallel:
    mpirun -np <N> python main.py
"""

import os
import sys

from PAOFLOW import PAOFLOW
from PAOFLOW.basis_gen import generate_basis_for_pseudo
from PAOFLOW.basis_gen.driver import _default_shells
from PAOFLOW.inputs.read_upf import UPF as _UPFParser

try:
    from mpi4py import MPI

    RANK = MPI.COMM_WORLD.Get_rank()
except ImportError:
    RANK = 0


from PAOFLOW import GPAO
from PAOFLOW.ACBN0 import ACBN0, eACBN0

# ----------------------------------------------------------------------- #
# Configuration  (edit freely)                                            #
# ----------------------------------------------------------------------- #
HERE = os.path.dirname(os.path.abspath(__file__))
PREFIX = 'As1Ga1'
UPFS = [os.path.join(HERE, 'As1Ga1.save/As.upf'), os.path.join(HERE, 'As1Ga1.save/Ga.upf')]
BASISPATH = os.path.join(HERE, 'BASIS_PS') + os.sep
OUT = 'output'

# Parallel launch commands and executable paths (edit to your machine).
MPI_QE = 'mpirun -np 18'
MPI_PY = 'mpirun -np 1'
MPI_HARTREE = 'mpirun -np 18'
QE_PATH = '/Users/marco/Local/Programs/qe-7.4.1/bin/'
PY_PATH = '/Users/marco/anaconda3/envs/work/bin/python'

PROJECTION = 'ortho-atomic'   # ortho-atomic projections fit the Hubbard U
CONV_THR = 0.05
IBRAV = 2
NK = 801

# Residual tolerance for the Gaussian fit of the pseudo wavefunctions.
# Loosen (e.g. 0.05 - 0.1) if ACBN0 raises "Could not optimize the wfcs";
# ONCV / fully-relativistic pseudos often need a looser value than 0.01.
GAUSSIAN_THRESHOLD = 0.05

# Hubbard manifolds and their initial U (eV).
HUBBARD_INIT = {
    'Ga-4s': 0.5,
    'Ga-4p': 0.5,
    'As-4s': 0.5,
    'As-4p': 0.5,
}

V_CUTOFF = 2.6   # intersite neighbour cutoff (Angstrom)
V_INIT = 0.5     # initial intersite V (eV)


def ensure_basis(preset="extended"):
    """Generate the pseudo-atom basis under BASISPATH for every species.

    The 'extended' preset is a superset of 'standard' and 'minimal', so
    generating it once is enough for every configuration used below.
    """
    if RANK != 0:
        return
    for upf_path in UPFS:
        upf = _UPFParser(upf_path)
        element = upf.element.strip()
        elem_dir = os.path.join(BASISPATH, element)
        expected = _default_shells(upf, preset=preset)
        missing = [
            s for s in expected
            if not os.path.exists(os.path.join(elem_dir, "{}.dat".format(s)))
        ]
        if missing:
            print("Generating pseudo-atom basis for {} under {} ...".format(
                element, BASISPATH))
            generate_basis_for_pseudo(
                upf_path, BASISPATH.rstrip(os.sep), preset=preset, verbose=True
            )
        else:
            print("Using existing pseudo-atom basis for {} under {}".format(
                element, BASISPATH))


def compute_bands(label):
    """Reconstruct the PAO band structure from the current <PREFIX>.save
    using the minimal basis and dump it to OUT/bands_<label>_0.dat.
    """
    p = PAOFLOW.PAOFLOW(
        workpath=HERE,
        outputdir=OUT,
        savedir='{}.save'.format(PREFIX),
        smearing='gauss',
        npool=1,
        verbose=False,
    )
    # Standard basis for the projections, as required for ACBN0.
    p.projections(basispath=BASISPATH, configuration='standard')
    p.projectability(pthr=0.95)
    p.pao_hamiltonian()
    p.bands(ibrav=IBRAV, nk=NK, fname='bands_{}'.format(label))
    p.finish_execution()


def main():
    ensure_basis(preset='extended')
    if "MPI" in globals():
        MPI.COMM_WORLD.Barrier()

    # ------------------------------------------------------------------ #
    # ACBN0: self-consistent on-site U                                    #
    # ------------------------------------------------------------------ #
    a = ACBN0(
        PREFIX,
        workdir='./',
        mpi_qe=MPI_QE,
        mpi_python=MPI_PY,
        mpi_hartree=MPI_HARTREE,
        qe_options='',
        qe_path=QE_PATH,
        python_path=PY_PATH,
        outputdir=OUT,
        projection=PROJECTION,
        use_local_basis=True,
        basispath=BASISPATH,
        configuration='standard',
        gaussian_threshold=GAUSSIAN_THRESHOLD,
    )
    a.set_hubbard_parameters(dict(HUBBARD_INIT))
    a.optimize_hubbard_U(convergence_threshold=CONV_THR)
    compute_bands('U')
    converged_U = dict(a.uVals)
    print('\nConverged U values:')
    for k, v in converged_U.items():
        print('  {} : {:.4f} eV'.format(k, v))

    # ------------------------------------------------------------------ #
    # eACBN0: joint on-site U + intersite V                               #
    # ------------------------------------------------------------------ #
    e = eACBN0(
        PREFIX,
        workdir='./',
        mpi_qe=MPI_QE,
        mpi_python=MPI_PY,
        mpi_hartree=MPI_HARTREE,
        qe_options='',
        qe_path=QE_PATH,
        python_path=PY_PATH,
        outputdir=OUT,
        projection=PROJECTION,
        use_local_basis=True,
        basispath=BASISPATH,
        configuration='standard',
        gaussian_threshold=GAUSSIAN_THRESHOLD,
    )
    e.set_hubbard_parameters(converged_U)
    e.set_intersite_pairs(cutoff=V_CUTOFF, V_init=V_INIT)
    e.print_intersite_pairs()
    e.optimize_hubbard_UV(convergence_threshold=CONV_THR, max_iter=25, mixing=0.7)
    e.run_dft(PREFIX, e.uspecies, e.uVals)
    compute_bands('UV')
    print('\nFinal U values:')
    for k, v in e.uVals.items():
        print('  {} : {:.4f} eV'.format(k, v))
    print('\nFinal V values:')
    for k, v in e.vVals.items():
        print('  {} : {:.4f} eV'.format(k, v))


if __name__ == "__main__":
    main()
