[build-system]
build-backend = "flit_core.buildapi"
requires = ["flit_core >=3.2,<4"]

[project]
name = "PAOFLOW"
readme = "README.md"
requires-python = ">=3.10"
license = { text = "GPL-3.0-or-later" }
authors = [{ name = "Marco Buongiorno Nardelli", email = "mbn@unt.edu" }]
keywords = ["DFT", "Hamiltonians", "PAO"]
dynamic = ["version", "description"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: POSIX :: Linux",
]
dependencies = ["numpy>=2.0,<2.3",
    "scipy>=1.14,<2",
    "mpi4py~=4.1",
    "pandas>=2.2,<3",]

[project.optional-dependencies]
weyl_search = ["z2pack", "tbmodels"]
graphics = ["vtk", "matplotlib","mendeleev"]
transport = ["psutil"]
pyskeaf = ["scikit-image>=0.20", "shapely>=2.0", "joblib>=1.2", "pandas>=2.0"]
phonon = ["phonopy>=2.21", "phono3py>=2.3", "seekpath>=2.0"]
fast = ["numba>=0.58"]
dev = ["pre-commit>=2.20.0", "pytest>=7"]
sparse = ["petsc4py", "slepc4py"]
docs = [
    "sphinx>=8",
    "myst-parser>=4",
    "myst-nb",
    "sphinx-design>=0.6",
    "sphinx-copybutton>=0.5",
    "pydata-sphinx-theme>=0.16",
    "sphinx-autobuild",
    "sphinx-autoapi",
]


[project.urls]
Homepage = "https://github.com/marcobn/PAOFLOW"

[project.scripts]
pyskeaf = "PAOFLOW.pyskeaf.cli:main"
paoflow-genbasis-ps = "PAOFLOW.basis_gen.cli:main"
paoflow-gen-qe = "PAOFLOW.gen.aflow_qe:main"
paoflow-gen = "PAOFLOW.gen.paoflow_driver:main"

[tool.ruff]
line-length = 100
lint.ignore = [
    "E711", # comparison to None should be 'if cond is None:'
    "E712", # comparison to True should be 'if cond is True:' or 'if cond:'
    "E722", # do not use bare except, specify exception instead
    "E731", # do not assign a lambda expression, use a def
    "E741", # ambiguous variable name 'l' (lowercase letter el)
    "E402", # module level import not at top of file
]

[tool.ruff.format]
quote-style = "single"

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "-ra"
