#!/usr/bin/env python3
"""PAOFLOW electron-phonon (Eliashberg) on EPW's coarse coupling (generated by paoflow_gen.py).

The coarse electron-phonon matrix elements come from EPW (``epbwrite = .true.``).
EPW evaluates both psi_k and psi_{k+q} from the nscf save, so the coupling shares
the band gauge of PAOFLOW's projections on that save, which the PAO
interpolation requires (docs/internals/Electron-Phonon-Coupling.md).

Two phases:

    python main.elphon.py inputs     # ph.x input, nscf K_POINTS list, epw.in (+ placeholder .ukk)
    mpirun -np N python main.elphon.py analyse   # PAO interpolation -> alpha^2F, lambda, Tc

Between them run, all in this directory (one QE outdir) and in this order:

    1. pw.x scf                         (with symmetry)
    2. ph.x  < <prefix>.ph.in           (irreducible q only)
    3. python <q-e>/EPW/bin/pp.py       (collects dvscf/patterns/dyn into save/)
    4. pw.x nscf with the K_POINTS card of nscf.kpoints   (full grid, explicit list)
    5. mpirun -np N epw.x -nk N -in epw.in   (writes <prefix>.epb*, one file per pool)

The nscf (4) overwrites <prefix>.save with the full-grid wavefunctions, so it
must come after ph.x and pp.py; save/ (dvscf, patterns, dyn) is not touched.
EPW and PAOFLOW then both read that nscf save.  Separate phonon/ and epw/
folders (as in the EPW tutorials) also work, but then the scf charge density
must be copied into epw/<prefix>.save before the nscf and dvscf_dir in epw.in
must point to ../phonon/save.

``epw.in`` written here runs EPW without any Wannier functions
(``wannierize = .false.``): EPW reads the band bookkeeping from the placeholder
<prefix>.ukk (EXCLUDE_BANDS, identity rotations) and writes the coarse coupling
before its Wannier stage, which PAOFLOW does not use.  Validated on Pb (EPW
tutorial 04): identical PAOFLOW results to a Wannierized EPW run.  An EPW input
with a Wannierization also works, as long as it sets ``epbwrite = .true.`` and
its outer disentanglement window contains every band.
"""

import argparse
import os
import sys

import numpy as np
from mpi4py import MPI

from PAOFLOW import PAOFLOW
from PAOFLOW.elphon.do_pao_eph import eliashberg_from_qe_coupling
from PAOFLOW.elphon.do_pao_eph_dense_q import eliashberg_dense_q
from PAOFLOW.elphon.elph_bloch import RY_TO_EV, read_nscf
from PAOFLOW.gen.epw_inputs import epw_input, kpoints_card, write_placeholder_ukk


# ----------------------------------------------------------------------- #
# Configuration  (edit freely -- masses / NELEC / NBND are system-specific) #
# ----------------------------------------------------------------------- #
HERE = os.path.dirname(os.path.abspath(__file__))
PREFIX = 'pb'
EPW_DIR = os.path.join(HERE, '.')    # EPW outdir: <prefix>.epb*, <prefix>.ukk
SAVEDIR = os.path.join(HERE, 'pb.save')    # the nscf save EPW read
OUTPUTDIR = 'output'
BASISDIR = os.path.join(HERE, 'BASIS_PS')

KGRID = (6, 6, 6)          # coarse k-grid (nscf, EPW nk1..3)
QGRID = (6, 6, 6)          # coarse q-grid (ph.x, EPW nq1..3); must divide KGRID
NBND = 16            # bands in the nscf run (> number of PAO orbitals)
EXCLUDE_BANDS = [1, 2, 3, 4, 5]  # 1-based bands left out of the coupling (e.g. semicore)
MASSES_AMU = [207.2]    # atomic mass of each species (amu)
NELEC = 14          # valence electrons (dense E_F recompute)
DENSE_Q = True      # interpolate q as well as k (recommended)
NK_DENSE = 48    # dense electron grid
NQ_DENSE = 24    # dense phonon grid (NK_DENSE % NQ_DENSE == 0)
SIGMA_EV = 0.05    # Fermi-surface smearing (eV), as EPW degaussw
MU_STAR = 0.1      # Coulomb pseudopotential for Tc
PTHR = 0.95            # projectability threshold

KB_EV = 8.617333262e-5


def _phonon_input():
    return '\n'.join([
        '&inputph',
        "  prefix='%s'," % PREFIX,
        "  outdir='./',",
        "  fildyn='%s.dyn'," % PREFIX,
        "  fildvscf='dvscf',",
        '  tr2_ph=1.0d-14,',
        '  ldisp=.true., nq1=%d, nq2=%d, nq3=%d,' % tuple(QGRID),
        '/',
        '',
    ])


def inputs():
    """Phase 1: ph.x input, nscf K_POINTS list, minimal epw.in and placeholder .ukk."""
    if any(k % q for k, q in zip(KGRID, QGRID)):
        sys.exit('QGRID %s must divide KGRID %s.' % (QGRID, KGRID))
    files = {
        PREFIX + '.ph.in': _phonon_input(),
        'nscf.kpoints': kpoints_card(KGRID),
        'epw.in': epw_input(PREFIX, MASSES_AMU, KGRID, QGRID, NBND - len(EXCLUDE_BANDS),
                            exclude_bands=EXCLUDE_BANDS),
    }
    for name, text in files.items():
        with open(os.path.join(HERE, name), 'w') as fh:
            fh.write(text)
        print('Wrote %s' % name)
    ukk = os.path.join(HERE, PREFIX + '.ukk')
    write_placeholder_ukk(ukk, NBND, KGRID[0] * KGRID[1] * KGRID[2],
                          exclude_bands=EXCLUDE_BANDS, nelec=NELEC)
    print('Wrote %s (+ empty .bvec/.mmn stubs) for wannierize=.false.; keep them in the epw.x run directory'
          % os.path.basename(ukk))
    print('Append nscf.kpoints to the pw.x nscf input (nbnd = %d), then run ph.x, pp.py, nscf, epw.x.'
          % NBND)


def pao_electronic_structure():
    """PAO projections and Hamiltonian on the EPW nscf save."""
    pf = PAOFLOW.PAOFLOW(workpath=HERE, outputdir=OUTPUTDIR, savedir=SAVEDIR,
                         save_overlaps=False, verbose=False)
    pf.projections(basispath=BASISDIR, configuration='standard')
    pf.projectability(pthr=PTHR)
    # The projections A_k = <phi|psi_k> rotate EPW's matrix elements to the PAO
    # gauge; pao_hamiltonian deletes them, so keep a copy first.
    projections = pf.data_controller.full_projections()[:, :, :, 0].copy()
    # The explicit K_POINTS list already spans the whole Brillouin zone.
    pf.pao_hamiltonian(expand_wedge=False)
    return projections, pf.data_controller.data_arrays['HRs'], read_nscf(SAVEDIR)


def analyse():
    """Phase 2: PAO interpolation of EPW's coupling -> alpha^2F, lambda, Tc."""
    if not os.path.isdir(SAVEDIR):
        sys.exit('%s not found. Run the pw.x nscf first.' % SAVEDIR)
    if not any(f.startswith(PREFIX + '.epb') for f in os.listdir(EPW_DIR)):
        sys.exit('No %s.epb* files in %s. Run epw.x with epbwrite = .true. first.' % (PREFIX, EPW_DIR))

    projections, HRs, nscf = pao_electronic_structure()
    lattice = (nscf['kpts_cryst'], nscf['bg'], nscf['at'])
    common = dict(source='epw', masses_amu=MASSES_AMU, nk_dense=NK_DENSE,
                  sigmas_ry=[SIGMA_EV / RY_TO_EV], nelec=NELEC, mu_star=MU_STAR)
    if DENSE_Q:
        # Coarse q-points and phonons come from the .epb files; the dense q-grid
        # is folded to its irreducible wedge.
        out = eliashberg_dense_q(
            projections, HRs, *lattice, EPW_DIR, tuple(QGRID), None, None, tuple(KGRID), None,
            nq_dense=NQ_DENSE, sym_rots=nscf['s_cryst'], tau_cryst=nscf['tau_cryst'],
            species=nscf['atom_names'], **common,
        )
    else:
        out = eliashberg_from_qe_coupling(
            projections, HRs, *lattice, EPW_DIR, None, tuple(KGRID), None, **common
        )

    # The result is identical on every rank; only rank 0 reports and writes files.
    if MPI.COMM_WORLD.Get_rank() != 0:
        return
    grids = 'k %d^3, q %s' % (NK_DENSE, ('%d^3' % NQ_DENSE) if DENSE_Q else 'coarse')
    print('PAOFLOW on EPW coupling (%s, %s, sigma %.3f eV):' % (PREFIX, grids, SIGMA_EV))
    print('  lambda   = %.4f' % out['lambda'])
    print('  w_log    = %.3f meV' % (out['omega_log'] * 1.0e3))
    print('  Tc (McM) = %.2f K   Tc (AD) = %.2f K   (mu* = %.2f)'
          % (out['Tc_mcmillan'], out['Tc_allen_dynes'], MU_STAR))
    outdir = os.path.join(HERE, OUTPUTDIR)
    os.makedirs(outdir, exist_ok=True)
    np.savetxt(os.path.join(outdir, 'alpha2F.dat'),
               np.column_stack([out['omega'] * 1.0e3, out['a2F']]),
               header='omega(meV)  alpha^2F  (lambda=%.4f, w_log=%.2fK, Tc_McM=%.3fK, Tc_AD=%.3fK, mu*=%.2f)'
               % (out['lambda'], out['omega_log'] / KB_EV, out['Tc_mcmillan'],
                  out['Tc_allen_dynes'], MU_STAR))
    np.savez(os.path.join(outdir, 'eliashberg.npz'), **out)
    print('  wrote %s/alpha2F.dat and eliashberg.npz' % OUTPUTDIR)


def main():
    parser = argparse.ArgumentParser(description='PAOFLOW electron-phonon on EPW coupling.')
    parser.add_argument('phase', nargs='?', choices=['inputs', 'analyse'], default='analyse',
                        help='inputs: write the QE/EPW inputs; analyse: PAOFLOW (default).')
    args = parser.parse_args()
    if args.phase == 'inputs':
        if MPI.COMM_WORLD.Get_rank() == 0:
            inputs()
    else:
        analyse()


if __name__ == '__main__':
    main()
