#!/usr/bin/env python3
"""PAOFLOW electron-phonon (Eliashberg) -- dense-q PAO route (generated by paoflow_gen.py).

EXPERIMENTAL extension of the PAO route that interpolates BOTH the electronic
k-grid and the phonon q-grid.  The coarse-q couplings are Fourier-transformed to
the double real-space vertex g(R_e, R_p); the phonons are Wigner-Seitz
interpolated directly from the coarse <prefix>.dyn files (no q2r).  Both are
evaluated on a dense NQ_DENSE^3 q-grid for alpha^2F, lambda, omega_log and Tc.

Two phases:

    python main.elphon.py inputs    # write the ph.x phonon + AHC templates
    python main.elphon.py analyse   # g(R_e,R_p) + dense-q interpolation -> Tc

The ``analyse`` phase distributes the dense-q loop over MPI ranks, so launch it
with mpirun for an (up to NQ_DENSE^3-fold) speedup::

    mpirun -np N python main.elphon.py analyse

Between them (same outdir), run the QE steps:

    1. phonon:  ph.x  < <prefix>.ph.in    # full DFPT dvscf on the coarse q-grid
    2. ahc:     ph.x  < <prefix>.ahc.in   # electron_phonon='ahc' -> ahc_dir/

IMPORTANT: the dense-q route needs the coupling AND the <prefix>.dyn files on the
FULL coarse q-grid (every q, not just the irreducible set).  Symmetry unfolding
of the coupling is not yet automated (see the do_pao_eph_dense_q TODOs), and the
polar (Frohlich) long-range term is not applied -- use it on metals (e.g. Pb).
"""

import argparse
import os
import sys

import numpy as np
from mpi4py import MPI

from PAOFLOW import PAOFLOW
from PAOFLOW.elphon.do_pao_eph_dense_q import (
    eliashberg_dense_q,
    phonon_interp_from_dyn,
)
from PAOFLOW.elphon.elph_bloch import read_nscf
from PAOFLOW.elphon.qe_elph_io import read_qe_dyn

# ----------------------------------------------------------------------- #
# Configuration  (edit freely -- masses / NELEC / NBND are system-specific) #
# ----------------------------------------------------------------------- #
HERE = os.path.dirname(os.path.abspath(__file__))
SAVEDIR = os.path.join(HERE, 'lead.save')
OUTPUTDIR = 'output'
PREFIX = 'lead'
BASISDIR = os.path.join(HERE, 'BASIS_PS')

# Coupling source:
#   'ahc'     -> unpatched QE AHC dumps (ahc_dir/ahc_gkk_iq<iq>.bin); NC pseudos.
#   'elphmat' -> patched-QE el_ph_mat dumps (elph_dir/elphmat.<iq>.dat); any pseudo.
SOURCE = 'ahc'
COUPLING_DIR = os.path.join(HERE, 'ahc_dir')

KGRID = (9, 9, 9)  # SCF / coupling k-grid (== pw.x K_POINTS)
QGRID = (6, 6, 6)  # coarse phonon q-grid (nq1, nq2, nq3)
NBND = 22  # bands in the nscf / AHC run (nbnd = ahc_nbnd)
MASSES_AMU = [207.2]  # atomic masses (amu), one per atom in the cell
NELEC = 14  # valence electrons (dense E_F recompute)
NK_DENSE = 42  # dense electron k-grid
NQ_DENSE = 42  # dense phonon q-grid
SIGMA_RY = 0.02  # Fermi-surface smearing (Ry)
MU_STAR = 0.1  # Coulomb pseudopotential for Tc
PTHR = 0.95  # projectability threshold


def _phonon_input():
    return '\n'.join(
        [
            '&inputph',
            "  prefix='%s'," % PREFIX,
            "  outdir='./',",
            "  fildyn='%s.dyn'," % PREFIX,
            "  fildvscf='dvscf',",
            '  tr2_ph=1.0d-12,',
            '  ldisp=.true., nq1=%d, nq2=%d, nq3=%d,' % (QGRID[0], QGRID[1], QGRID[2]),
            '/',
            '',
        ]
    )


def _ahc_input():
    return '\n'.join(
        [
            '&inputph',
            "  prefix='%s'," % PREFIX,
            "  outdir='./',",
            "  fildyn='%s.dyn'," % PREFIX,
            "  fildvscf='dvscf',",
            "  electron_phonon='ahc',",
            '  ahc_nbnd=%d, ahc_nbndskip=0, skip_upperfan=.true.,' % NBND,
            "  ahc_dir='ahc_dir/',",
            '  ldisp=.true., nq1=%d, nq2=%d, nq3=%d,' % (QGRID[0], QGRID[1], QGRID[2]),
            '/',
            '',
        ]
    )


def inputs():
    """Phase 1: write the ph.x phonon + AHC input templates."""
    ph = os.path.join(HERE, PREFIX + '.ph.in')
    ahc = os.path.join(HERE, PREFIX + '.ahc.in')
    with open(ph, 'w') as fh:
        fh.write(_phonon_input())
    with open(ahc, 'w') as fh:
        fh.write(_ahc_input())
    print('Wrote %s' % ph)
    print('Wrote %s' % ahc)
    print('Run (same outdir), then `analyse`:')
    print('  1) ph.x  < %s' % os.path.basename(ph))
    print('  2) ph.x  < %s' % os.path.basename(ahc))


def analyse():
    """Phase 2: g(R_e,R_p) + dense-q interpolation -> alpha^2F, lambda, Tc."""
    if not os.path.isdir(SAVEDIR):
        sys.exit('%s not found. Run pw.x (nscf) first.' % SAVEDIR)
    if not os.path.isdir(COUPLING_DIR):
        sys.exit(
            '%s not found. Run the QE phonon + AHC steps first (phase: inputs).' % COUPLING_DIR
        )

    pf = PAOFLOW.PAOFLOW(
        workpath=HERE,
        outputdir=OUTPUTDIR,
        savedir=SAVEDIR,
        save_overlaps=False,
        verbose=False,
    )
    pf.projections(basispath=BASISDIR, configuration='standard')
    pf.projectability(pthr=PTHR)
    # Grab the projection matrices A_k BEFORE pao_hamiltonian (which deletes them).
    # U is kept scattered over k-points, so ask for it explicitly.
    A = pf.data_controller.full_projections()[:, :, :, 0].copy()
    pf.pao_hamiltonian()
    HRs = pf.data_controller.data_arrays['HRs']
    info = read_nscf(SAVEDIR)

    # FULL coarse q-grid: one <prefix>.dyn per q, index-matched to the couplings.
    nq_full = QGRID[0] * QGRID[1] * QGRID[2]
    dyn_paths = [os.path.join(HERE, '%s.dyn%d' % (PREFIX, i + 1)) for i in range(nq_full)]
    q_coarse = np.array(
        [
            np.linalg.solve(info['bg'].T, np.asarray(read_qe_dyn(p)['q'], dtype=float))
            for p in dyn_paths
        ]
    )

    # phonons interpolated straight from the coarse dyn files (no q2r).
    phonon_at_q = phonon_interp_from_dyn(dyn_paths, tuple(QGRID), info['bg'], info['at'])

    out = eliashberg_dense_q(
        A,
        HRs,
        info['kpts_cryst'],
        info['bg'],
        info['at'],
        COUPLING_DIR,
        tuple(QGRID),
        q_coarse,
        dyn_paths,
        tuple(KGRID),
        phonon_at_q,
        nq_dense=NQ_DENSE,
        source=SOURCE,
        masses_amu=MASSES_AMU,
        nk_dense=NK_DENSE,
        sigmas_ry=[SIGMA_RY],
        nelec=NELEC,
        mu_star=MU_STAR,
        sym_rots=info['s_cryst'],
        tau_cryst=info['tau_cryst'],
        species=info['atom_names'],
    )

    # The Eliashberg result is identical on every rank (Allreduce inside the
    # driver); only rank 0 reports and writes the output files.
    if MPI.COMM_WORLD.Get_rank() != 0:
        return

    kB = 8.617333262e-5  # eV/K
    print(
        'PAO dense-q Eliashberg (%s, source=%s, Nk=%d, Nq=%d):'
        % (PREFIX, SOURCE, NK_DENSE, NQ_DENSE)
    )
    print('  lambda   = %.4f' % out['lambda'])
    print('  <w_log>  = %.1f K' % (out['omega_log'] / kB))
    print('  Tc (McM) = %.2f K  (mu* = %.3f)' % (out['Tc_mcmillan'], MU_STAR))
    print('  Tc (AD)  = %.2f K  (mu* = %.3f)' % (out['Tc_allen_dynes'], MU_STAR))

    outdir = os.path.join(HERE, OUTPUTDIR)
    os.makedirs(outdir, exist_ok=True)
    a2f = os.path.join(outdir, 'alpha2F.dat')
    np.savetxt(
        a2f,
        np.column_stack([out['omega'] * 1.0e3, out['a2F']]),
        header='omega(meV)   alpha^2F(omega)   '
        '(lambda=%.4f, omega_log=%.2fK, Tc_McM=%.3fK, Tc_AD=%.3fK, mu*=%.3f)'
        % (
            out['lambda'],
            out['omega_log'] / kB,
            out['Tc_mcmillan'],
            out['Tc_allen_dynes'],
            MU_STAR,
        ),
    )
    npz = os.path.join(outdir, 'eliashberg.npz')
    np.savez(npz, **out)
    print('  wrote %s' % a2f)
    print('  wrote %s' % npz)


def main():
    parser = argparse.ArgumentParser(description='PAOFLOW electron-phonon dense-q (PAO) workflow.')
    parser.add_argument(
        'phase',
        nargs='?',
        choices=['inputs', 'analyse', 'all'],
        default='all',
        help='Workflow phase to run (default: all).',
    )
    args = parser.parse_args()
    if args.phase in ('inputs', 'all'):
        inputs()
    if args.phase in ('analyse', 'all'):
        analyse()


if __name__ == '__main__':
    main()
