"""Generate QE inputs for an unreconstructed Si(001) slab.

Produces the upper panel of Fig. 10 of the PAOFLOW paper: a finite slab whose
bands are projected onto the two outermost atomic planes. The companion
calculation in the parent directory computes the same quantity for a
semi-infinite crystal via the NEGF surface Green's function (lower panel).

The slab reuses the (1x1) surface cell of the bulk run -- simple tetragonal with
a_tet = a_cub/sqrt(2) -- so both calculations share the same surface Brillouin
zone and the same Gamma-Xbar path, which is what makes the two panels
comparable.

Layers stack along z with spacing a_cub/4, and the in-plane position cycles
with period four:

    (0,0) -> (1/2,0) -> (1/2,1/2) -> (0,1/2) -> ...

Surfaces are left unpassivated: the dangling bonds are the whole point of the
figure. That makes the slab metallic, hence the smearing in the QE inputs.

Run ``python build_slab.py`` to (re)write ``scf.in`` and ``nscf.in``.
"""

import numpy as np

# Cubic lattice constant of diamond Si, matching the bulk run (bohr).
A_CUB = 10.599478
# In-plane lattice constant of the (1x1) (001) surface cell.
A_TET = A_CUB / np.sqrt(2.0)
# Spacing between consecutive (001) atomic planes.
D_LAYER = A_CUB / 4.0
# Vacuum thickness separating periodic images along z (bohr).
VACUUM = 30.0

# Number of atomic planes. 32 reproduces the paper; the PAO basis is 9 orbitals
# per atom, so nbnd = 9*NLAYERS and the nscf cost grows steeply. 16 layers is
# enough to converge the surface states and runs in a fraction of the time.
NLAYERS = 16

# In-plane fractional positions of the four inequivalent (001) planes.
_PATTERN = [(0.0, 0.0), (0.5, 0.0), (0.5, 0.5), (0.0, 0.5)]

PSEUDO = 'Si.pbe-tm-new-gipaw-v2.1.UPF'
PREFIX = 'silicon_slab'


def slab_geometry(nlayers=NLAYERS):
    """Return ``(celldm3, positions)`` for an ``nlayers``-thick Si(001) slab.

    ``positions`` is an ``(nlayers, 3)`` array of crystal coordinates, with the
    slab centred in the cell along z.
    """
    thickness = (nlayers - 1) * D_LAYER
    c = thickness + VACUUM
    z0 = 0.5 * VACUUM

    positions = np.empty((nlayers, 3))
    for n in range(nlayers):
        x, y = _PATTERN[n % 4]
        positions[n] = (x, y, (z0 + n * D_LAYER) / c)

    return c / A_TET, positions


def _positions_block(positions):
    return '\n'.join(' Si %10.8f %10.8f %10.8f' % tuple(p) for p in positions)


_TEMPLATE = """ &control
    calculation = '{calculation}'
    prefix='{prefix}',
    pseudo_dir = '../'
    outdir='./output/qe'
 /
 &system
!   Si(001) slab, {nlayers} atomic planes, unpassivated on both faces.
!   Generated by build_slab.py -- edit NLAYERS there, do not hand-edit this file.
!   Same (1x1) surface cell as the bulk run, so Gamma-Xbar is identical.
    ibrav=  6, celldm(1) = {a_tet:.9f}, celldm(3) = {celldm3:.9f},
    nat= {nlayers}, ntyp= 1,
    ecutwfc = 18.0,{extra_system}
!   Dangling bonds make the slab metallic.
    occupations = 'smearing', smearing = 'mv', degauss = 0.01
 /
 &electrons
    mixing_mode = 'plain'
    mixing_beta = 0.3
    conv_thr = {conv_thr}
 /
ATOMIC_SPECIES
 Si  28.086 {pseudo}
ATOMIC_POSITIONS (crystal)
{positions}
K_POINTS {{automatic}}
  {kmesh} 0 0 0
"""


def write_inputs(nlayers=NLAYERS):
    celldm3, positions = slab_geometry(nlayers)
    common = dict(
        prefix=PREFIX,
        nlayers=nlayers,
        a_tet=A_TET,
        celldm3=celldm3,
        pseudo=PSEUDO,
        positions=_positions_block(positions),
    )

    with open('scf.in', 'w') as f:
        f.write(
            _TEMPLATE.format(
                calculation='scf', extra_system='', conv_thr='1.0d-10', kmesh='8 8 1', **common
            )
        )

    # PAOFLOW needs a uniform Gamma-centred mesh and the full PAO manifold:
    # nbnd must be at least nawf = 9 orbitals x nlayers atoms.
    with open('nscf.in', 'w') as f:
        f.write(
            _TEMPLATE.format(
                calculation='nscf',
                extra_system=f'  nbnd = {9 * nlayers}, nosym=.true., noinv=.true.,',
                conv_thr='1.0d-8',
                kmesh='6 6 1',
                **common,
            )
        )

    print(f'wrote scf.in and nscf.in for a {nlayers}-layer Si(001) slab')
    print(f'  c/a_tet = {celldm3:.4f}   nbnd = {9 * nlayers}   nawf = {9 * nlayers}')


if __name__ == '__main__':
    write_inputs()
