//! Golden-value parity tests against the pure-Python `pyints` kernel.
//!
//! The reference values are generated by `scripts/gen_golden.py` and stored in
//! `tests/golden.json`. Regenerate them whenever the Python reference changes.

use paoflow_acbn0_rs::eri::{contr_coulomb, coulomb_repulsion, Cgbf};
use paoflow_acbn0_rs::special::{b_array, binomial_prefactor, fgamma, gammln};
use serde_json::Value;
use std::fs;
use std::path::PathBuf;

const RTOL: f64 = 1e-12;

fn load_golden() -> Value {
    let mut path = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    path.push("tests/golden.json");
    let text =
        fs::read_to_string(&path).unwrap_or_else(|e| panic!("cannot read {}: {e}", path.display()));
    serde_json::from_str(&text).expect("invalid golden.json")
}

fn close(got: f64, want: f64) -> bool {
    let denom = want.abs().max(1e-300);
    if want.abs() < 1e-300 {
        got.abs() < 1e-12
    } else {
        ((got - want).abs() / denom) < RTOL
    }
}

#[test]
fn gammln_matches_reference() {
    let data = load_golden();
    for case in data["gammln"].as_array().unwrap() {
        let x = case["x"].as_f64().unwrap();
        let want = case["val"].as_f64().unwrap();
        let got = gammln(x);
        assert!(close(got, want), "gammln({x}): got {got}, want {want}");
    }
}

#[test]
fn fgamma_matches_reference() {
    let data = load_golden();
    for case in data["fgamma"].as_array().unwrap() {
        let m = case["m"].as_i64().unwrap();
        let x = case["x"].as_f64().unwrap();
        let want = case["val"].as_f64().unwrap();
        let got = fgamma(m, x);
        assert!(close(got, want), "fgamma({m},{x}): got {got}, want {want}");
    }
}

#[test]
fn binomial_prefactor_matches_reference() {
    let data = load_golden();
    for case in data["binomial_prefactor"].as_array().unwrap() {
        let s = case["s"].as_i64().unwrap();
        let ia = case["ia"].as_i64().unwrap();
        let ib = case["ib"].as_i64().unwrap();
        let xpa = case["xpa"].as_f64().unwrap();
        let xpb = case["xpb"].as_f64().unwrap();
        let want = case["val"].as_f64().unwrap();
        let got = binomial_prefactor(s, ia, ib, xpa, xpb);
        assert!(
            close(got, want),
            "binomial_prefactor({s},{ia},{ib},{xpa},{xpb}): got {got}, want {want}"
        );
    }
}

#[test]
fn b_array_matches_reference() {
    let data = load_golden();
    for case in data["b_array"].as_array().unwrap() {
        let args: Vec<f64> = case["args"]
            .as_array()
            .unwrap()
            .iter()
            .map(|v| v.as_f64().unwrap())
            .collect();
        let want: Vec<f64> = case["val"]
            .as_array()
            .unwrap()
            .iter()
            .map(|v| v.as_f64().unwrap())
            .collect();
        let got = b_array(
            args[0] as i64,
            args[1] as i64,
            args[2] as i64,
            args[3] as i64,
            args[4],
            args[5],
            args[6],
            args[7],
            args[8],
            args[9],
            args[10],
            args[11],
            args[12],
        );
        assert_eq!(got.len(), want.len(), "b_array length mismatch");
        for (i, (g, w)) in got.iter().zip(want.iter()).enumerate() {
            assert!(close(*g, *w), "b_array[{i}]: got {g}, want {w}");
        }
    }
}

fn xyz3(v: &Value) -> [f64; 3] {
    let a = v.as_array().unwrap();
    [
        a[0].as_f64().unwrap(),
        a[1].as_f64().unwrap(),
        a[2].as_f64().unwrap(),
    ]
}

fn lmn3(v: &Value) -> [i64; 3] {
    let a = v.as_array().unwrap();
    [
        a[0].as_i64().unwrap(),
        a[1].as_i64().unwrap(),
        a[2].as_i64().unwrap(),
    ]
}

fn f64vec(v: &Value) -> Vec<f64> {
    v.as_array()
        .unwrap()
        .iter()
        .map(|x| x.as_f64().unwrap())
        .collect()
}

#[test]
fn coulomb_repulsion_matches_reference() {
    let data = load_golden();
    for case in data["coulomb_repulsion"].as_array().unwrap() {
        // Each centre is [xyz, norm, lmn, alpha].
        let prim = |k: &str| {
            let p = case[k].as_array().unwrap();
            (
                xyz3(&p[0]),
                p[1].as_f64().unwrap(),
                lmn3(&p[2]),
                p[3].as_f64().unwrap(),
            )
        };
        let (axyz, an, almn, aa) = prim("a");
        let (bxyz, bn, blmn, ba) = prim("b");
        let (cxyz, cn, clmn, ca) = prim("c");
        let (dxyz, dn, dlmn, da) = prim("d");
        let want = case["val"].as_f64().unwrap();
        let got = coulomb_repulsion(
            &axyz, an, &almn, aa, &bxyz, bn, &blmn, ba, &cxyz, cn, &clmn, ca, &dxyz, dn, &dlmn, da,
        );
        assert!(
            close(got, want),
            "coulomb_repulsion: got {got}, want {want}"
        );
    }
}

fn cgbf_from(v: &Value) -> Cgbf {
    Cgbf {
        origin: xyz3(&v["xyz"]),
        exps: f64vec(&v["exps"]),
        coefs: f64vec(&v["coefs"]),
        norms: f64vec(&v["norms"]),
        powers: v["pow"].as_array().unwrap().iter().map(lmn3).collect(),
    }
}

#[test]
fn contr_coulomb_matches_reference() {
    let data = load_golden();
    for case in data["contr_coulomb"].as_array().unwrap() {
        let a = cgbf_from(&case["a"]);
        let b = cgbf_from(&case["b"]);
        let c = cgbf_from(&case["c"]);
        let d = cgbf_from(&case["d"]);
        let want = case["val"].as_f64().unwrap();
        let got = contr_coulomb(&a, &b, &c, &d);
        assert!(close(got, want), "contr_coulomb: got {got}, want {want}");
    }
}
